name = "consent-dashboard-keep-alive"
main = "keep-alive-worker.js"
compatibility_date = "2024-04-01"

[build]
command = ""

[env.production]
compatibility_date = "2024-04-01"

# Enable logs
[triggers]
logpush = true

[triggers.logpush]
retention = "24h"
format = "json"
