name: Daily Data Fetch

on:
  schedule:
    # รันทุกวันเวลา 05:00 น. ตามเวลาไทย (22:00 UTC)
    - cron: '0 22 * * *'
        # ตั้ง timezone เป็น Asia/Bangkok
        # หมายเหตุ: GitHub Actions ใช้ UTC ดังนั้นต้องคำนวณเวลาให้ตรงกับ 05:00 น. ไทย (22:00 UTC)

  # อนุญาตให้รันด้วยตนเองได้
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd scripts
        npm install
        
    - name: Run fetch
      run: |
        cd scripts
        node fetch_all.js
      env:
        # ใส่ environment variables ที่จำเป็น
        NODE_ENV: production
